### ISSUE TITLE
$kernel->terminate() unavailable (and debug toolbar missing)

### ISSUE THREAD

**Issue by pbowyer** [dantleech/sf-http-cache-tagging#5]
I've been digging in as I have a need for this - and haven't seen middleware for Symfony before, so it's good fun!

With the current repository, testing on Symfony 2.8, I was failing on `$kernel->terminate()` in the following:

``` php
$kernel = new AppKernel('dev', true);
$kernel->loadClassCache();
$appStore = new Store($kernel->getCacheDir().'/http_cache');
$cacheKernel = new HttpCache($kernel, $appStore);
$tagStore = new DoctrineCache(new PhpFileCache($kernel->getCacheDir().'/http_cache_tags'));
$tagManager = new TagManager($tagStore, $appStore);
$kernel = new \DTL\Symfony\HttpCacheTagging\TaggingKernel($cacheKernel, $tagManager);

$request = Request::createFromGlobals();
$response = $kernel->handle($request);
$response->send();
#error_log($kernel->getLog());
$kernel->terminate($request, $response);
```

To work around that I modified `TaggingKernel.php` to start:

``` php
class TaggingKernel extends \AppKernel implements HttpKernelInterface
```

This fixes that, but the web debug toolbar is now AWOL ("An error occurred while loading the web debug toolbar (404: Not Found).  Do you want to open the profiler?"). It was working before re-wrapping the kernel - do you have any ideas? Thanks.

**Comment by dantleech** [comment]
I guess we should also implement the `TerminableInterface` (as indicated in [this article](http://www.sitepoint.com/stackphp-explained/)).

I am actually testing this with a custom kernel which does implement `TerminableInterface`, here: https://github.com/sulu-io/sulu-standard/pull/641/files#diff-fe706955fac058f123c21f3e427b40d6R26

**Comment by dantleech** [comment]
Now implemented, thanks.
